language: go

go:
    - 1.8
    - 1.8.x

matrix:
  allow_failures:
- go: 1.8.x

script: 
  - go get -u github.com/golang/dep/...
  - dep ensure 
  - go install github.com/acm-uiuc/arbor
  
notifications:
  email: false
